version: '3'

#networks:
#  sb:
#    driver: bridge

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    #networks:
    #  - sb
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    #networks:
    #  - sb
    ports:
      - "9092:9092"
    environment: 
      #KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "iss:1:1" #, test-topic2:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper
    #  - producer
    #  - consumer

  influxdb:
    # InfluxDB Version 1.8.0. Not tagged as latest because soon InfluxDB 2.0 will
    # released, bringing major changes
    image: influxdb:1.8.0
    #Expose port 8086
    #networks:
    #  - sb
    ports:
      - '8086:8086'
    #Persistant volume for data
    volumes:
      - influxdb-storage:/var/lib/influxdb
    #Environment variables for setting credentials, taken from a .env file
    environment:
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  
  grafana:
    #Local image or Docker Hub image
    image: grafana/grafana
    #Expose port 3000
    ports:
      - '3000:3000'
    #Allow link to influxdb container
    #networks:
    #  - sb
    links:
      - influxdb
    #Environment variables for setting credentials, taken from a .env file
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_INSTALL_PLUGINS=pr0ps-trackmap-panel
  
  producer:
    #Local image or Docker Hub image
    image: producer
    container_name: producer
    #Simulate tty console
    tty: true
    #networks:
    #  - sb
    #Allow link to influxdb container
    links:
    #  - influxdb
      - kafka
  
  consumer:
    image: consumer
    container_name: consumer
    tty: true
    #networks:
    #  - sb
    links:
      - influxdb
      - kafka

volumes:
  influxdb-storage:
