version: '3'

services:

  zookeeper:
    #Latest wurstmeister/zookeeper image from the docker hub
    image: wurstmeister/zookeeper
    tmpfs: "/datalog"
    #Accessible though port 2181
    ports:
      - "2181:2181"

  kafka:
    #Latests wurstmeister/zookeeper image from the docker hub
    image: wurstmeister/kafka
    #Accessible through port 9092
    ports:
      - "9092:9092"
    #Configuration of the brokers and topics.
    # - Hostname of the broker: kafka
    # - Topic: sat-data, Partition: 1, Replication: 1
    # - Connected to zookeeper trough port 2181
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "sat-data:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    #Link to zookeeper
    links:
      - zookeeper
    #volumes:
    # - /var/run/docker.sock:/var/run/docker.sock

  influxdb:
    #InfluxDB Version 1.8.0. Not tagged as latest because soon InfluxDB 2.0 will be released, bringing major changes
    image: influxdb:1.8.0
    #Accessible trough port 8086
    ports:
      - '8086:8086'
    #Persistant volume for data
    volumes:
      - influxdb-storage:/var/lib/influxdb
    #Environment variables for setting credentials, taken from a .env file
    environment:
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  
  grafana:
    #Local image or Docker Hub image
    #image: grafana/grafana
    image: freil10/grafana
    #Expose port 3000
    ports:
      - '3000:3000'
    #Allow link to influxdb container
    links:
      - influxdb
    #Environment variables for setting credentials, taken from a .env file
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_INSTALL_PLUGINS=pr0ps-trackmap-panel
  
  producer_n2yo:
    #Local image or Docker Hub image
    #image: producer_n2yo
    image: freil10/producer_n2yo
    #Link to kafka
    links:
      - kafka
  
  producer_wiss:
    #Local image or Docker Hub image
    #image: producer_wiss
    image: freil10/producer_wiss
    #Link to kafka
    links:
      - kafka

  consumer:
    #image: consumer
    image: freil10/consumer
    links:
      - influxdb
      - kafka

volumes:
  influxdb-storage:
